<?xml version="1.0" encoding="utf-8"?><Database Name="StatesDatabase" Class="StatesDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\StatesDatabase.mdf;Integrated Security=True" SettingsObjectName="J_Pitts_Lab_3.Properties.Settings" SettingsPropertyName="StatesDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Population" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FlagDescription" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="StateFlower" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateBird" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateColors" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LargestCities" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Capital" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MedianIncome" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ComputerJobPercent" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>